application: sorkin-signature
version: 15
runtime: python27
api_version: 1
threadsafe: true

handlers:


- url: /a/.*
  script: sorkin.signature.api.wsgi

- url: /cron/.*
  script: sorkin.signature.cron.wsgi
  login: admin

- url: /setup
  static_files: www/setup.html
  upload: www/setup.html
  login: required

- url: /panel(/.*)?
  static_files: www/panel.html
  upload: www/panel.html
  login: required


- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /
  static_dir: www

libraries:
- name: webapp2
  version: "2.5.2"

- name: pycrypto
  version: "2.6"

